"""Supervision pivot stage D - Israeli defect catalog seed (30+ items)."""

from __future__ import annotations

SUPERVISION_CATALOG_VERSION = "1.4.0-supervision-checklist"

_CHECKLIST_SCOPE_APARTMENT = "APARTMENT"
_CHECKLIST_SCOPE_PUBLIC_AREA = "PUBLIC_AREA"
_CHECKLIST_SCOPE_BOTH = "BOTH"

_STAGE_STRUCTURE = ("STRUCTURE",)
_STAGE_FINISHING = ("FINISHING",)

SUPERVISION_CATALOG_ISSUES: tuple[dict, ...] = (
    {
        "issue_id": "QC-STR-001",
        "catalog_reference_id": "IL-STD-466-STEEL-COVER",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "REINFORCEMENT_STEEL",
        "category_name_he": "ברזל זיון",
        "category_standard_id": 'ת"י 466 חלק 1',
        "target_elements": "קורות, עמודים, תקרות",
        "issue_name_he": "כיסוי בטון לא מספיק בזיון חשוף",
        "standard_ref": 'ת"י 466 חלק 1',
        "severity": "High",
        "description": "זיון חשוף ללא כיסוי בטון מתוכנן לפני יציקה.",
        "engineering_impact": "קורוזיה וירידת דבק בטון-פלדה.",
        "rectification_action": "להתקין ספייסרים ולאשר לפני יציקה.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "QC-STR-002",
        "catalog_reference_id": "IL-STD-466-CONCRETE-TEST",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "CONCRETE_PLACING",
        "category_name_he": "יציקת בטון",
        "category_standard_id": 'ת"י 466',
        "target_elements": "יסודות, קורות, תקרות",
        "issue_name_he": "יציקה ללא בדיקת תכולות",
        "standard_ref": 'ת"י 466',
        "severity": "Critical",
        "description": "בוצעה יציקה ללא תיעוד תכולות וסומך.",
        "engineering_impact": "חולשת מבנית נסתרת.",
        "rectification_action": "לעצור ולבצע בדיקה לפי הנחיית מהנדס.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "SUP-STR-003",
        "catalog_reference_id": "IL-STD-466-CRACK-STRUCT",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "STRUCTURAL_ELEMENTS",
        "category_name_he": "אלמנטים קונסטרוקטיביים",
        "category_standard_id": 'ת"י 466',
        "target_elements": "קירות, תקרות, עמודים",
        "issue_name_he": "סדקים עוברים / קונסטרוקטיביים",
        "standard_ref": 'ת"י 466',
        "severity": "Critical",
        "description": "סדקים אורכיים/אלכסוניים בקיר בטון.",
        "engineering_impact": "חולשה מבנית; דליפת מים.",
        "rectification_action": "להמתין להנחיית מהנדס קונסטרוקציה.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "SUP-STR-004",
        "catalog_reference_id": "IL-STD-466-LAP-SPLICE",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "REINFORCEMENT_STEEL",
        "category_name_he": "ברזל זיון",
        "category_standard_id": 'ת"י 466',
        "target_elements": "קורות, עמודים",
        "issue_name_he": "חיבורי ברזל לא תקניים (חפיפה קצרה)",
        "standard_ref": 'ת"י 466',
        "severity": "Critical",
        "description": "אורך חפיפה בין מוטות קטן מהנדרש בתוכנית.",
        "engineering_impact": "חולשה בנקודת המשך.",
        "rectification_action": "להאריך/לרתך לפי תוכנית.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "SUP-STR-005",
        "catalog_reference_id": "IL-STD-118-CONCRETE-GRADE",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "CONCRETE_PLACING",
        "category_name_he": "יציקת בטון",
        "category_standard_id": 'ת"י 118',
        "target_elements": "קורות, תקרות",
        "issue_name_he": "בטון לא תואם סימון במשאית",
        "standard_ref": 'ת"י 118',
        "severity": "Critical",
        "description": "תעודת משלוח אינה תואמת דרגת בטון.",
        "engineering_impact": "חוזק סופי לא יעמוד בדרישות.",
        "rectification_action": "לפסול משאית; לא לשפוך.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "SUP-STR-006",
        "catalog_reference_id": "IL-STD-118-SHORING",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "FORMWORK_AND_SHORING",
        "category_name_he": "טפסנות וחיזוקים",
        "category_standard_id": 'ת"י 118',
        "target_elements": "טפסנות, חיזוקים",
        "issue_name_he": "עמודי חיזוק לא יציבים",
        "standard_ref": 'ת"י 118',
        "severity": "Critical",
        "description": "מערכת חיזוק זמנית רופפת.",
        "engineering_impact": "סכנת התמוטטות.",
        "rectification_action": "לעצור עבודה; לייצב לפני המשך.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "PARKING",
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "SUP-STR-007",
        "catalog_reference_id": "IL-STD-940-PILE-DEPTH",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "FOUNDATIONS_AND_PILING",
        "category_name_he": "יסודות וכלונסאות",
        "category_standard_id": 'ת"י 940',
        "target_elements": "כלונסאות, יסודות",
        "issue_name_he": "אי-התאמת עומק קידוח כלונס לתוכנית",
        "standard_ref": 'ת"י 940',
        "severity": "High",
        "description": "עומק הקידוח נמוך מהמתוכנן.",
        "engineering_impact": "שקיעה דיפרנציאלית.",
        "rectification_action": "לעצור; להמתין להנחיית מהנדס.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "SUP-STR-008",
        "catalog_reference_id": "IL-STD-466-NEGATIVE-STEEL",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "REINFORCEMENT_STEEL",
        "category_name_he": "ברזל זיון",
        "category_standard_id": 'ת"י 466',
        "target_elements": "תקרות",
        "issue_name_he": "זיון שלילי חסר בתקרה",
        "standard_ref": 'ת"י 466',
        "severity": "Critical",
        "description": "ברזל עליון בתקרה חסר.",
        "engineering_impact": "סיכון קריסת תקרה.",
        "rectification_action": "להשלים זיון שלילי לפני יציקה.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "SUP-STR-009",
        "catalog_reference_id": "IL-STD-466-PARKING-SLAB",
        "top_family": "STRUCTURAL_WORKS",
        "category_id": "STRUCTURAL_ELEMENTS",
        "category_name_he": "אלמנטים קונסטרוקטивיים",
        "category_standard_id": 'ת"י 466',
        "target_elements": "תקרת חניון, רamps",
        "issue_name_he": "סדקים בלוח רצפת חניון",
        "standard_ref": 'ת"י 466',
        "severity": "High",
        "description": "סדקים פעילים בלוח בטון בחניון.",
        "engineering_impact": "חדירת מים וחלודת זיון.",
        "rectification_action": "להמתין להנחיית מהנדס; לתקן איטום.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "PARKING",
        "allowed_stages": _STAGE_STRUCTURE,
    },
    {
        "issue_id": "QC-INS-001",
        "catalog_reference_id": "IL-STD-2752-RAIL-SEAL",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "WATERPROOFING",
        "category_name_he": "איטום",
        "category_standard_id": 'ת"י 2752',
        "target_elements": "גגות, מרפסות",
        "issue_name_he": "יריעת איטום לא מחוברת למעקה",
        "standard_ref": 'ת"י 2752',
        "severity": "High",
        "description": "חיבור יריעה למעקה/סף לא תקין.",
        "engineering_impact": "חדירת מים למבנה.",
        "rectification_action": "להלחים ולאטום לפי יצרן.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "QC-INS-002",
        "catalog_reference_id": "IL-STD-1045-INSULATION-GAP",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "THERMAL_INSULATION",
        "category_name_he": "בידוד תרמי",
        "category_standard_id": 'ת"י 1045',
        "target_elements": "חזיתות, גג",
        "issue_name_he": "רציפות בידוד נשברה",
        "standard_ref": 'ת"י 1045',
        "severity": "Medium",
        "description": "קפיצות/חורים בבידוד תרמי.",
        "engineering_impact": "גשר תרמי ורטיבות.",
        "rectification_action": "להשלים בידוד רציף.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "BALCONY_ROOF",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-INS-003",
        "catalog_reference_id": "IL-STD-949-WATER",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "FACADE_WATERPROOFING",
        "category_name_he": "איטום חזיתות",
        "category_standard_id": 'ת"י 949',
        "target_elements": "חזית, מרפסות",
        "issue_name_he": "כשל קפילארי / רטיבות מעל פנלים",
        "standard_ref": 'ת"י 949',
        "severity": "High",
        "description": "רטיבות בחזית מעל פנלים.",
        "engineering_impact": "חדירת מים פנימית.",
        "rectification_action": "לטפל במערכת איטום חיצונית.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-INS-004",
        "catalog_reference_id": "IL-STD-1752-FLOOR-WALL",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "ROOFS_AND_BALCONIES",
        "category_name_he": "גגות ומרפסות",
        "category_standard_id": 'ת"י 1752 ח"1',
        "target_elements": "מרפסות, גגות",
        "issue_name_he": "חוסר רולקות בחיבור רצפה-קיר במרפסת",
        "standard_ref": 'ת"י 1752 ח"1',
        "severity": "Critical",
        "description": "זווית רצפה-קיר חדה ללא רולקה.",
        "engineering_impact": "קריעת יריעת איטום.",
        "rectification_action": "להתקין רולקה ואיטום.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-INS-005",
        "catalog_reference_id": "IL-STD-2752-DRAIN-LINK",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "ROOFS_AND_BALCONIES",
        "category_name_he": "גגות ומרפסות",
        "category_standard_id": 'ת"י 2752',
        "target_elements": "גגות, מרפסות",
        "issue_name_he": "מרזב לא מחובר לאיטום",
        "standard_ref": 'ת"י 2752',
        "severity": "High",
        "description": "חיבור מרזב רופף.",
        "engineering_impact": "דליפה.",
        "rectification_action": "לחבר אטום.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "BALCONY_ROOF",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-INS-006",
        "catalog_reference_id": "IL-STD-2752-WET-CORNERS",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "WET_ROOMS",
        "category_name_he": "חדרים רטובים",
        "category_standard_id": 'הל"ת',
        "target_elements": "מקלחות, שירותים",
        "issue_name_he": "איטום רציף לא בוצע בפינות",
        "standard_ref": 'הל"ת',
        "severity": "High",
        "description": "פינות ללא רולקה/רשת.",
        "engineering_impact": "דליפה.",
        "rectification_action": "רולקה+איטום.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-INS-007",
        "catalog_reference_id": "IL-STD-1752-BASEMENT-WATER",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "UNDERGROUND_STRUCTURES",
        "category_name_he": "מרתפים",
        "category_standard_id": 'ת"י 1752',
        "target_elements": "קירות מרתף",
        "issue_name_he": "חדירת מים פעילה במרתף",
        "standard_ref": 'ת"י 1752',
        "severity": "Critical",
        "description": "זרימת מים בקיר מרתף.",
        "engineering_impact": "נזק מבנה.",
        "rectification_action": "לעצור; איטום+ניקוז.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "PARKING",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-INS-008",
        "catalog_reference_id": "IL-STD-2752-EXPANSION-JOINT",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "EXPANSION_AND_JOINTS",
        "category_name_he": "תפרים והתפשטות",
        "category_standard_id": 'ת"י 2752',
        "target_elements": "תפרי התפשטות",
        "issue_name_he": "תפר התפשטות לא אטום",
        "standard_ref": 'ת"י 2752',
        "severity": "High",
        "description": "תפר פתוח.",
        "engineering_impact": "חדירת מים.",
        "rectification_action": "לסגור באיטום גמיש.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "BALCONY_ROOF",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-INS-009",
        "catalog_reference_id": "IL-STD-2752-SHARED-WET",
        "top_family": "SYSTEM_WATERPROOFING_AND_INSULATION",
        "category_id": "WET_ROOMS",
        "category_name_he": "חדרים רטובים",
        "category_standard_id": 'הל"ת',
        "target_elements": "שירותים משותפים, מקלחות משותפות",
        "issue_name_he": "איטום לקוי בחדר רטוב משותף",
        "standard_ref": 'הל"ת',
        "severity": "High",
        "description": "איטום רציף חסר או פגום בחדר רטוב משותף.",
        "engineering_impact": "דליפה לקומות סמוכות.",
        "rectification_action": "לתקן איטום רציף לפי תקן.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "WET_ROOMS",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "QC-MEP-001",
        "catalog_reference_id": "IL-STD-1205-PRESSURE-TEST",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "PLUMBING",
        "category_name_he": "אינסטלציה",
        "category_standard_id": 'ת"י 1205',
        "target_elements": "צנרת, נקודות מים",
        "issue_name_he": "בדיקת לחץ לא בוצעה",
        "standard_ref": 'ת"י 1205',
        "severity": "High",
        "description": "לא בוצעה בדיקת לחץ לפני סגירת קירות.",
        "engineering_impact": "נזילות נסתרות.",
        "rectification_action": "לבצע בדיקת לחץ ולתעד.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "QC-MEP-002",
        "catalog_reference_id": "IL-STD-60364-PANEL-GUARD",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "ELECTRICAL",
        "category_name_he": "חשמל",
        "category_standard_id": 'ת"י 60364',
        "target_elements": "לוחות, נקודות",
        "issue_name_he": "חוסר אביזר הגנה בלוח חשמל",
        "standard_ref": 'ת"י 60364',
        "severity": "Critical",
        "description": "לוח חשמל ללא אביזרי הגנה.",
        "engineering_impact": "סיכון בטיחותי.",
        "rectification_action": "להשלים הגנה לפני חיבור.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-003",
        "catalog_reference_id": "IL-STD-1205-DRAIN-SLOPE",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "PLUMBING",
        "category_name_he": "אינסטלציה",
        "category_standard_id": 'ת"י 1205 ח"3',
        "target_elements": "מרפסות, מקלחות",
        "issue_name_he": "היעדר שיפועי ניקוז במרפסת/מקלחת",
        "standard_ref": 'ת"י 1205 ח"3',
        "severity": "Medium",
        "description": "שיפוע ניקוז לא תקין.",
        "engineering_impact": "עמידת מים.",
        "rectification_action": "לתקן שיפוע.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-004",
        "catalog_reference_id": "IL-STD-1205-TRAP-MISSING",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "PLUMBING_AND_DRAINAGE",
        "category_name_he": "אינסטלציה וביוב",
        "category_standard_id": 'הל"ת',
        "target_elements": "שופכין, ניקוז",
        "issue_name_he": "מחסום ריח חסר בשופכין",
        "standard_ref": 'הל"ת',
        "severity": "High",
        "description": "לא הותקן מחסום ריח.",
        "engineering_impact": "ריחות ביוב.",
        "rectification_action": "להתקין מחסום תקני.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-005",
        "catalog_reference_id": "IL-STD-60364-GFCI",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "ELECTRICAL_INSTALLATIONS",
        "category_name_he": "חשמל",
        "category_standard_id": "תקנות החשמל",
        "target_elements": "מטבח, חדר רטוב",
        "issue_name_he": "שקעים במטבח/רטוב ללא מגן",
        "standard_ref": "תקנות החשמל",
        "severity": "Critical",
        "description": "שקעים ללא הגנת דליפה.",
        "engineering_impact": "התחשמלות.",
        "rectification_action": "להתקין מגן דליפה.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-006",
        "catalog_reference_id": "IL-STD-1220-SMOKE-DET",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "FIRE_SAFETY_SYSTEMS",
        "category_name_he": "מערכות בטיחות",
        "category_standard_id": 'ת"י 1220',
        "target_elements": "דירות, מסדרונות",
        "issue_name_he": "גלאי עשן לא מותקן בחדר",
        "standard_ref": 'ת"י 1220',
        "severity": "Critical",
        "description": "חסר גלאי לפי תקן.",
        "engineering_impact": "גילוי מאוחר.",
        "rectification_action": "להתקין לפי תוכנית.",
        "scope": _CHECKLIST_SCOPE_BOTH,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-007",
        "catalog_reference_id": "IL-STD-5281-AC-DRAIN",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "HVAC_SYSTEMS",
        "category_name_he": "מיזוג אוויר",
        "category_standard_id": 'ת"י 5281',
        "target_elements": "מזגנים, ניקוז",
        "issue_name_he": "ניקוז מזגן לא מחובר",
        "standard_ref": 'ת"י 5281',
        "severity": "High",
        "description": "צינור ניקוז פתוח.",
        "engineering_impact": "רטיבות קיר.",
        "rectification_action": "לחבר לניקוז.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-008",
        "catalog_reference_id": "IL-STD-GAS-LEAK-SUSPECT",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "GAS_INSTALLATIONS",
        "category_name_he": "גז",
        "category_standard_id": "תקנות הגז",
        "target_elements": "צנרת גז",
        "issue_name_he": "דליפת גז חשודה",
        "standard_ref": "תקנות הגז",
        "severity": "Critical",
        "description": "ריח גז בדירה.",
        "engineering_impact": "סיכון פיצוץ.",
        "rectification_action": "לנתק; לקרוא טכנאי.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-009",
        "catalog_reference_id": "IL-STD-60364-LOBBY-EMERGENCY",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "ELECTRICAL_INSTALLATIONS",
        "category_name_he": "חשמל",
        "category_standard_id": 'ת"י 60364',
        "target_elements": "לובי, מסדרונות",
        "issue_name_he": "תאורת חירום לקויה בלובי",
        "standard_ref": 'ת"י 60364',
        "severity": "High",
        "description": "תאורת חירום לא פועלת או חסרה בלובי.",
        "engineering_impact": "פינוי מסוכן בחירום.",
        "rectification_action": "לתקן/להשלים תאורת חירום.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "LOBBY",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-010",
        "catalog_reference_id": "IL-STD-1205-SHARED-DRAIN",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "PLUMBING_AND_DRAINAGE",
        "category_name_he": "אינסטלציה וביוב",
        "category_standard_id": 'ת"י 1205 ח"3',
        "target_elements": "שירותים משותפים",
        "issue_name_he": "שיפוע ניקוז לקוי בחדר רטוב משותף",
        "standard_ref": 'ת"י 1205 ח"3',
        "severity": "High",
        "description": "שיפוע רצפה בחדר רטוב משותף לא עומד בדרישה.",
        "engineering_impact": "עמידת מים ורטיבות.",
        "rectification_action": "לתקן שיפוע ניקוז.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "WET_ROOMS",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-011",
        "catalog_reference_id": "IL-STD-1220-ELEVATOR-PHONE",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "FIRE_SAFETY_SYSTEMS",
        "category_name_he": "מערכות בטיחות",
        "category_standard_id": 'ת"י 1220',
        "target_elements": "מעליות, חדרי מדרגות",
        "issue_name_he": "טלפון חירום במעלית לא תקין",
        "standard_ref": 'ת"י 1220',
        "severity": "Critical",
        "description": "קשר חירום במעלית לא פועל.",
        "engineering_impact": "לכודים ללא קשר בחירום.",
        "rectification_action": "לתקן מערכת קשר חירום.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "ELEVATOR_STAIRS",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-MEP-012",
        "catalog_reference_id": "IL-STD-60364-OUTDOOR-LIGHT",
        "top_family": "MECHANICAL_ELECTRICAL_SYSTEMS",
        "category_id": "ELECTRICAL_INSTALLATIONS",
        "category_name_he": "חשמל",
        "category_standard_id": 'ת"י 60364',
        "target_elements": "שטח חוץ, גינון",
        "issue_name_he": "תאורת חוץ לא תקינה",
        "standard_ref": 'ת"י 60364',
        "severity": "Medium",
        "description": "גופי תאורה חיצוניים לא פועלים או חשופים.",
        "engineering_impact": "סיכון בטיחותי בלילה.",
        "rectification_action": "לתקן/להחליף גופי תאורה.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "OUTDOOR",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "QC-FIN-001",
        "catalog_reference_id": "IL-STD-466-CRACK-PLASTER",
        "top_family": "FINISHING_WORKS",
        "category_id": "PLASTER_AND_PAINT",
        "category_name_he": "טיח וצבע",
        "category_standard_id": 'ת"י 466 חלק 2',
        "target_elements": "קירות, תקרות",
        "issue_name_he": "סדקים פעילים לפני שכבת גמר",
        "standard_ref": 'ת"י 466 חלק 2',
        "severity": "Medium",
        "description": "סדקים בטיח לפני צביעה/ריצוף.",
        "engineering_impact": "התפשטות סדקים.",
        "rectification_action": "לטפל במקור הסדק.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "QC-FIN-002",
        "catalog_reference_id": "IL-STD-4458-SLOPE-WET",
        "top_family": "FINISHING_WORKS",
        "category_id": "TILING",
        "category_name_he": "ריצוף וחיפוי",
        "category_standard_id": 'ת"י 4458',
        "target_elements": "רצפות, קירות רטובים",
        "issue_name_he": "שיפוע לא מספיק בחדר רטוב",
        "standard_ref": 'ת"י 4458',
        "severity": "High",
        "description": "שיפוע ריצוף בחדר רטוב לא עומד בדרישה.",
        "engineering_impact": "הצטברות מים.",
        "rectification_action": "לתקן שיפוע.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-003",
        "catalog_reference_id": "IL-STD-1928-TILE-LEVEL",
        "top_family": "FINISHING_WORKS",
        "category_id": "TILING",
        "category_name_he": "ריצוף וחיפוי",
        "category_standard_id": 'ת"י 1928',
        "target_elements": "קירות, רצפות",
        "issue_name_he": "סטייה באנכיות/מישוריות חיפוי",
        "standard_ref": 'ת"י 1928',
        "severity": "Low",
        "description": "סטייה במישוריות/אנכיות חיפוי.",
        "engineering_impact": "פגם אסתטי ובטיחותי.",
        "rectification_action": "ליישר תשתית.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-004",
        "catalog_reference_id": "IL-STD-1555-GROUT-GAP",
        "top_family": "FINISHING_WORKS",
        "category_id": "TILING",
        "category_name_he": "ריצוף וחיפוי",
        "category_standard_id": 'ת"י 1555',
        "target_elements": "חדרים רטובים",
        "issue_name_he": "פוגות לא מלאות/לא אטומות",
        "standard_ref": 'ת"י 1555',
        "severity": "Medium",
        "description": "רובה פוגות חסרה או סדוקה.",
        "engineering_impact": "חדירת מים.",
        "rectification_action": "למלא/לאטום פוגות.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-005",
        "catalog_reference_id": "IL-STD-1090-WINDOW-SEAL",
        "top_family": "FINISHING_WORKS",
        "category_id": "DOORS_AND_WINDOWS",
        "category_name_he": "חלונות ודלתות",
        "category_standard_id": 'ת"י 1090',
        "target_elements": "חלונות, משקופים",
        "issue_name_he": "חלון ללא איטום היקפי",
        "standard_ref": 'ת"י 1090',
        "severity": "High",
        "description": "לא בוצע איטום בין משקוף לקיר.",
        "engineering_impact": "חדירת מי גשם.",
        "rectification_action": "לאטום לפי יצרן.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-006",
        "catalog_reference_id": "IL-STD-1555-SILICONE",
        "top_family": "FINISHING_WORKS",
        "category_id": "PAINTING_AND_FINISHES",
        "category_name_he": "צבע וגמרים",
        "category_standard_id": 'ת"י 1555',
        "target_elements": "אמבטיות, מקלחות",
        "issue_name_he": "סיליקון באמבטיה לא אטום",
        "standard_ref": 'ת"י 1555',
        "severity": "High",
        "description": "סיליקון סדוק/חסר.",
        "engineering_impact": "רטיבות.",
        "rectification_action": "להסיר ולסילקון מחדש.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-007",
        "catalog_reference_id": "IL-STD-1555-STAIR-SLIP",
        "top_family": "FINISHING_WORKS",
        "category_id": "INTERIOR_SYSTEMS",
        "category_name_he": "מערכות פנים",
        "category_standard_id": 'ת"י 1555',
        "target_elements": "מדרגות",
        "issue_name_he": "ריצוף מדרגות חלק",
        "standard_ref": 'ת"י 1555',
        "severity": "High",
        "description": "מדרגות ללא מנגנון נגד החלקה.",
        "engineering_impact": "סכנת החלקה.",
        "rectification_action": "להוסיף מחגור/שכבה.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "ELEVATOR_STAIRS",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-008",
        "catalog_reference_id": "IL-STD-789-PAINT-WET",
        "top_family": "FINISHING_WORKS",
        "category_id": "PAINTING_AND_FINISHES",
        "category_name_he": "צבע וגמרים",
        "category_standard_id": 'ת"י 789',
        "target_elements": "קירות, תקרות",
        "issue_name_he": "צבע על טיח לא יבש",
        "standard_ref": 'ת"י 789',
        "severity": "Medium",
        "description": "צבע יושם על טיח לח.",
        "engineering_impact": "קילופים.",
        "rectification_action": "לייבש; לצבוע מחדש.",
        "scope": _CHECKLIST_SCOPE_APARTMENT,
        "public_area_id": None,
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-009",
        "catalog_reference_id": "IL-STD-1928-LOBBY-FLOOR",
        "top_family": "FINISHING_WORKS",
        "category_id": "TILING",
        "category_name_he": "ריצוף וחיפוי",
        "category_standard_id": 'ת"י 1928',
        "target_elements": "לובי, כניסה",
        "issue_name_he": "ריצוף לובי לא שטוח / פגום",
        "standard_ref": 'ת"י 1928',
        "severity": "Medium",
        "description": "סדקים או סטייה במישוריות ריצוף לובי.",
        "engineering_impact": "סכנת מעידות.",
        "rectification_action": "לתקן/להחליף ריצוף.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "LOBBY",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-010",
        "catalog_reference_id": "IL-STD-789-LOBBY-PAINT",
        "top_family": "FINISHING_WORKS",
        "category_id": "PLASTER_AND_PAINT",
        "category_name_he": "טיח וצבע",
        "category_standard_id": 'ת"י 789',
        "target_elements": "קירות לובי, תקרה",
        "issue_name_he": "גמר קירות/תקרה לקוי בלובי",
        "standard_ref": 'ת"י 789',
        "severity": "Low",
        "description": "קילופים, בליטות או סדקים בגמר לובי.",
        "engineering_impact": "פגם אסתטי.",
        "rectification_action": "לתקן טיח/צבע.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "LOBBY",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-011",
        "catalog_reference_id": "IL-STD-1928-SHARED-WET-TILE",
        "top_family": "FINISHING_WORKS",
        "category_id": "TILING",
        "category_name_he": "ריצוף וחיפוי",
        "category_standard_id": 'ת"י 1928',
        "target_elements": "שירותים משותפים",
        "issue_name_he": "חיפוי לקוי בחדר רטוב משותף",
        "standard_ref": 'ת"י 1928',
        "severity": "Medium",
        "description": "אריחים רופפים או סדוקים בחדר רטוב משותף.",
        "engineering_impact": "חדירת מים.",
        "rectification_action": "להחליף/לחזק חיפוי.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "WET_ROOMS",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-012",
        "catalog_reference_id": "IL-STD-1555-STAIR-RAIL",
        "top_family": "FINISHING_WORKS",
        "category_id": "INTERIOR_SYSTEMS",
        "category_name_he": "מערכות פנים",
        "category_standard_id": 'ת"י 1555',
        "target_elements": "מעקות, מדרגות",
        "issue_name_he": "מעקה מדרגות רופף או חסר",
        "standard_ref": 'ת"י 1555',
        "severity": "Critical",
        "description": "מעקה לא יציב או חסר בחדר מדרגות.",
        "engineering_impact": "סכנת נפילה.",
        "rectification_action": "להתקין/לחזק מעקה.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "ELEVATOR_STAIRS",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-013",
        "catalog_reference_id": "IL-STD-1928-OUTDOOR-PAVE",
        "top_family": "FINISHING_WORKS",
        "category_id": "TILING",
        "category_name_he": "ריצוף וחיפוי",
        "category_standard_id": 'ת"י 1928',
        "target_elements": "ריצוף חוץ, מדרכות",
        "issue_name_he": "ריצוף חוץ לא שטוח / פגום",
        "standard_ref": 'ת"י 1928',
        "severity": "Medium",
        "description": "סדקים או הפרשי גובה בריצוף חוץ.",
        "engineering_impact": "סכנת מעידות.",
        "rectification_action": "לתקן/להחליף ריצוף.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "OUTDOOR",
        "allowed_stages": _STAGE_FINISHING,
    },
    {
        "issue_id": "SUP-FIN-014",
        "catalog_reference_id": "IL-STD-789-OUTDOOR-FENCE",
        "top_family": "FINISHING_WORKS",
        "category_id": "PAINTING_AND_FINISHES",
        "category_name_he": "צבע וגמרים",
        "category_standard_id": 'ת"י 789',
        "target_elements": "גדרות, קירות חוץ",
        "issue_name_he": "גמר חיצוני לקוי (גדר/קיר)",
        "standard_ref": 'ת"י 789',
        "severity": "Low",
        "description": "קילופים או חלודה בגמר חיצוני.",
        "engineering_impact": "התדרדרות מהירה.",
        "rectification_action": "לתקן/לצבוע מחדש.",
        "scope": _CHECKLIST_SCOPE_PUBLIC_AREA,
        "public_area_id": "OUTDOOR",
        "allowed_stages": _STAGE_FINISHING,
    },
)
